/* Yalla — seed data + bilingual strings. Invented data for a course demo. */
/* ponytail: plain globals (no modules) so index.html runs from file:// with no server. */

window.CITIES = [
  { key: "tel-aviv",  he: "תל אביב",   en: "Tel Aviv" },
  { key: "jerusalem", he: "ירושלים",   en: "Jerusalem" },
  { key: "beer-sheva",he: "באר שבע",    en: "Be'er Sheva" },
];

/* real lat/lng centers for the map; per-activity coords are derived from x/y around these */
window.CITY_CENTER = {
  "tel-aviv":   { lat: 32.0809, lng: 34.7806, zoom: 13, span:{lat:0.045,lng:0.05} },
  "jerusalem":  { lat: 31.7800, lng: 35.2190, zoom: 14, span:{lat:0.01, lng:0.01} },
  "beer-sheva": { lat: 31.2540, lng: 34.7960, zoom: 13, span:{lat:0.05, lng:0.06} },
};

window.INTERESTS = [
  { key: "sport",   he: "ספורט",      en: "Sport",        icon: "⚽" },
  { key: "outdoors",he: "טבע",         en: "Outdoors",     icon: "🥾" },
  { key: "food",    he: "אוכל",        en: "Food",         icon: "🍽️" },
  { key: "music",   he: "מוזיקה",      en: "Music",        icon: "🎶" },
  { key: "language",he: "שפה",         en: "Language",     icon: "🗣️" },
  { key: "career",  he: "קריירה",      en: "Career",       icon: "💼" },
  { key: "culture", he: "תרבות",       en: "Culture",      icon: "🎭" },
  { key: "dance",   he: "ריקוד",       en: "Dance",        icon: "💃" },
  { key: "social",  he: "חברתי",       en: "Social",       icon: "🥂" },
  { key: "tech",    he: "טכנולוגיה",   en: "Tech",         icon: "💻" },
];

/* x/y = percentage position on the stylized city map */
window.ACTIVITIES = [
  { id:"a1", city:"tel-aviv", emoji:"🏐", cat:"sport",
    title:{he:"ליגת כדורעף שקיעה",en:"Sunset Beach Volleyball"},
    blurb:{he:"משחקים על חוף גורדון בכל יום שלישי, כל הרמות מוזמנות.",en:"Pickup games on Gordon beach every Tuesday — all levels welcome."},
    tags:["sport","social"], when:{he:"שלישי · 18:00",en:"Tue · 18:00"}, distanceKm:2.3, attendees:24, x:30, y:42 },
  { id:"a2", city:"tel-aviv", emoji:"🗣️", cat:"language",
    title:{he:"עברית על חומוס",en:"Hebrew over Hummus"},
    blurb:{he:"שיחה קלה בעברית סביב צלחת חומוס — בלי לחץ, רק כיף.",en:"Casual Hebrew practice over a plate of hummus — zero pressure."},
    tags:["language","food","social"], when:{he:"רביעי · 19:30",en:"Wed · 19:30"}, distanceKm:1.1, attendees:12, x:46, y:55 },
  { id:"a3", city:"tel-aviv", emoji:"🧗", cat:"sport",
    title:{he:"טיפוס למתחילים",en:"Bouldering for Beginners"},
    blurb:{he:"קיר בולדר ידידותי, נעליים בהשאלה, קהילה חמה.",en:"Friendly bouldering wall, rental shoes, warm crowd."},
    tags:["sport"], when:{he:"ראשון · 20:00",en:"Sun · 20:00"}, distanceKm:3.8, attendees:18, x:62, y:30 },
  { id:"a4", city:"tel-aviv", emoji:"🏄", cat:"sport",
    title:{he:"שיעור גלישה ראשון",en:"First Surf Lesson"},
    blurb:{he:"גלשן וחליפה כלולים, מדריך דובר אנגלית.",en:"Board and wetsuit included, English-speaking instructor."},
    tags:["sport","outdoors"], when:{he:"שישי · 07:30",en:"Fri · 07:30"}, distanceKm:4.5, attendees:8, x:34, y:62 },
  { id:"a5", city:"tel-aviv", emoji:"💃", cat:"dance",
    title:{he:"לילה של סלסה",en:"Newcomers Salsa Night"},
    blurb:{he:"שיעור פתיחה למתחילים ואז ריקוד חופשי עד מאוחר.",en:"Beginner class first, then open dancing till late."},
    tags:["dance","social"], when:{he:"חמישי · 21:00",en:"Thu · 21:00"}, distanceKm:2.0, attendees:40, x:54, y:72 },
  { id:"a6", city:"tel-aviv", emoji:"💼", cat:"career",
    title:{he:"ערב נטוורקינג להייטק",en:"Startup Networking Night"},
    blurb:{he:"הכירו עולים שעובדים בהייטק — בירה ראשונה עלינו.",en:"Meet olim working in tech — first beer's on us."},
    tags:["career","tech","social"], when:{he:"שני · 19:00",en:"Mon · 19:00"}, distanceKm:1.7, attendees:55, x:38, y:24 },
  { id:"a7", city:"jerusalem", emoji:"🕯️", cat:"social",
    title:{he:"ארוחת שישי לעולים",en:"Shabbat Dinner for Olim"},
    blurb:{he:"שולחן גדול, אוכל ביתי, אנשים חדשים בדיוק כמוך.",en:"Big table, home cooking, people as new here as you."},
    tags:["social","food","culture"], when:{he:"שישי · 19:00",en:"Fri · 19:00"}, distanceKm:1.4, attendees:16, x:50, y:48 },
  { id:"a8", city:"jerusalem", emoji:"📷", cat:"culture",
    title:{he:"צילום בעיר העתיקה",en:"Old City Photo Walk"},
    blurb:{he:"סיור צילום בשעת הזהב דרך השווקים והסמטאות.",en:"Golden-hour photo walk through the markets and alleys."},
    tags:["culture","outdoors"], when:{he:"שבת · 16:30",en:"Sat · 16:30"}, distanceKm:2.6, attendees:14, x:64, y:60 },
  { id:"a9", city:"jerusalem", emoji:"🍅", cat:"food",
    title:{he:"סיור טעימות במחנה יהודה",en:"Machane Yehuda Tasting Tour"},
    blurb:{he:"טועמים את השוק עם מקומי שיודע איפה הדברים הטובים.",en:"Taste the shuk with a local who knows the good stuff."},
    tags:["food","culture"], when:{he:"חמישי · 17:00",en:"Thu · 17:00"}, distanceKm:1.0, attendees:10, x:30, y:38 },
  { id:"a10", city:"beer-sheva", emoji:"🌄", cat:"outdoors",
    title:{he:"זריחה במכתש",en:"Crater Sunrise Hike"},
    blurb:{he:"יוצאים לפני אור ראשון, קפה שחור על המצוק.",en:"Out before first light, black coffee on the cliff edge."},
    tags:["outdoors","sport"], when:{he:"שבת · 05:00",en:"Sat · 05:00"}, distanceKm:6.2, attendees:9, x:24, y:30 },
  { id:"a11", city:"beer-sheva", emoji:"💻", cat:"career",
    title:{he:"מיטאפ מתכנתים גב-ים",en:"Gav-Yam Coders Meetup"},
    blurb:{he:"הרצאה קצרה ואז פיצה וקוד עם הקהילה הטכנולוגית בדרום.",en:"Short talk then pizza and code with the southern tech scene."},
    tags:["career","tech"], when:{he:"שלישי · 18:30",en:"Tue · 18:30"}, distanceKm:3.1, attendees:28, x:58, y:52 },
  { id:"a12", city:"beer-sheva", emoji:"🥋", cat:"sport",
    title:{he:"קרב מגע למתחילים",en:"Krav Maga Basics"},
    blurb:{he:"שיעור היכרות, ביטחון עצמי וקצת זיעה.",en:"Intro class — confidence, fundamentals, and a good sweat."},
    tags:["sport"], when:{he:"ראשון · 19:00",en:"Sun · 19:00"}, distanceKm:2.2, attendees:15, x:44, y:66 },
  { id:"a13", city:"beer-sheva", emoji:"🥏", cat:"sport",
    title:{he:"פריזבי על הדשא בבן גוריון",en:"Frisbee on the BGU Lawn"},
    blurb:{he:"אולטימייט פריזבי אחר הצהריים, כל הרמות מוזמנות.",en:"Afternoon ultimate frisbee — all levels welcome."},
    tags:["sport","social"], when:{he:"שני · 17:00",en:"Mon · 17:00"}, distanceKm:1.2, attendees:16, x:60, y:40 },
  { id:"a14", city:"beer-sheva", emoji:"🏃", cat:"sport",
    title:{he:"ריצת לילה על הטיילת",en:"Night Run on the Promenade"},
    blurb:{he:"5 ק\"מ קלילים בקצב נוח, נפגשים ורצים יחד.",en:"Easy 5K at a chill pace — we meet and run together."},
    tags:["sport","outdoors"], when:{he:"שלישי · 20:30",en:"Tue · 20:30"}, distanceKm:1.8, attendees:22, x:48, y:58 },
  { id:"a15", city:"beer-sheva", emoji:"♟️", cat:"social",
    title:{he:"ערב משחקי קופסה באגודה",en:"Board Games at the Student Union"},
    blurb:{he:"קטאן, קוד שמות ועוד — מגיעים, מתחלקים לשולחנות ומשחקים.",en:"Catan, Codenames and more — show up, split into tables, play."},
    tags:["social"], when:{he:"רביעי · 19:00",en:"Wed · 19:00"}, distanceKm:0.9, attendees:14, x:64, y:50 },
  { id:"a16", city:"beer-sheva", emoji:"🎤", cat:"culture",
    title:{he:"מיקרופון פתוח בעיר העתיקה",en:"Open Mic in the Old City"},
    blurb:{he:"מוזיקה, סטנדאפ או שירה — הבמה פתוחה, הקהל חם.",en:"Music, stand-up or poetry — open stage, warm crowd."},
    tags:["culture","music","social"], when:{he:"חמישי · 21:00",en:"Thu · 21:00"}, distanceKm:2.0, attendees:30, x:40, y:66 },
  { id:"a17", city:"beer-sheva", emoji:"🧘", cat:"outdoors",
    title:{he:"יוגה בפארק הנחל",en:"Yoga in Nahal Park"},
    blurb:{he:"בוקר שקט על הדשא, מחצלות בהשאלה, פתוח לכולם.",en:"Quiet morning on the grass, mats provided, open to all."},
    tags:["outdoors","sport"], when:{he:"ראשון · 07:00",en:"Sun · 07:00"}, distanceKm:1.5, attendees:12, x:54, y:34 },
  { id:"a18", city:"beer-sheva", emoji:"☕", cat:"language",
    title:{he:"קפה והחלפת שפות",en:"Language Exchange Café"},
    blurb:{he:"חצי שעה עברית, חצי שעה אנגלית — וקפה טוב בדרך.",en:"Half an hour Hebrew, half English — and good coffee throughout."},
    tags:["language","social"], when:{he:"שני · 18:30",en:"Mon · 18:30"}, distanceKm:1.1, attendees:10, x:46, y:48 },
  { id:"a19", city:"beer-sheva", emoji:"🧗", cat:"sport",
    title:{he:"קיר טיפוס בדרום",en:"Climbing Wall South"},
    blurb:{he:"בולדרינג מקורה, נעליים בהשאלה, מתחילים מוזמנים.",en:"Indoor bouldering, rental shoes, beginners welcome."},
    tags:["sport"], when:{he:"רביעי · 20:00",en:"Wed · 20:00"}, distanceKm:2.4, attendees:18, x:66, y:62 },
];

/* likesYou: true => a right-swipe triggers an instant match (scripted for the demo) */
window.PEOPLE = [
  { id:"p1", name:"Maya", age:26, flag:"🇫🇷", city:"tel-aviv", color:"#FF6B6B", likesYou:true, distanceKm:1.2,
    country:{he:"צרפת",en:"France"}, langs:["FR","EN","עברית"],
    interests:["sport","food","culture"],
    bio:{he:"עליתי מפריז לפני 4 חודשים. גולשת, שותה יותר מדי קפה, מחפשת עם מי לטפס.",en:"Made aliyah from Paris 4 months ago. Surfer, too much coffee, looking for climbing partners."} },
  { id:"p2", name:"Daniel", age:29, flag:"🇺🇸", city:"tel-aviv", color:"#1FB6A6", likesYou:false, distanceKm:3.4,
    country:{he:"ארה\"ב",en:"USA"}, langs:["EN","עברית"],
    interests:["career","sport","tech"],
    bio:{he:"מהנדס מבוסטון. כדורסל בשישי, סטארטאפים בשאר הזמן.",en:"Engineer from Boston. Basketball on Fridays, startups the rest of the week."} },
  { id:"p3", name:"Sofía", age:24, flag:"🇦🇷", city:"tel-aviv", color:"#E63E8C", likesYou:true, distanceKm:2.1,
    country:{he:"ארגנטינה",en:"Argentina"}, langs:["ES","EN"],
    interests:["dance","music","food"],
    bio:{he:"מבואנוס איירס. רוקדת סלסה, מבשלת אמפנדס, תמיד למעלה למשהו ספונטני.",en:"From Buenos Aires. Salsa dancer, empanada cook, always up for something spontaneous."} },
  { id:"p4", name:"Lev", age:27, flag:"🇺🇦", city:"jerusalem", color:"#FF9E5E", likesYou:false, distanceKm:1.9,
    country:{he:"אוקראינה",en:"Ukraine"}, langs:["RU","EN","עברית"],
    interests:["outdoors","music","tech"],
    bio:{he:"מקייב. שחמט, טיולים, ומחפש חבר'ה לג'אם בגיטרה.",en:"From Kyiv. Chess, hiking, and hunting for people to jam guitar with."} },
  { id:"p5", name:"Tamar", age:25, flag:"🇿🇦", city:"tel-aviv", color:"#FFCB47", likesYou:true, distanceKm:0.8,
    country:{he:"דרום אפריקה",en:"South Africa"}, langs:["EN","עברית"],
    interests:["culture","social","outdoors"],
    bio:{he:"מקייפטאון. צלמת, חולת שווקים, חדשה בעיר ורעבה לחברים.",en:"From Cape Town. Photographer, market addict, new in town and hungry for friends."} },
  { id:"p6", name:"Noah", age:28, flag:"🇨🇦", city:"jerusalem", color:"#7F77DD", likesYou:false, distanceKm:4.0,
    country:{he:"קנדה",en:"Canada"}, langs:["EN","FR"],
    interests:["food","language","social"],
    bio:{he:"ממונטריאול. לומד עברית בקושי, אבל מצוין בלמצוא חומוס טוב.",en:"From Montréal. Barely learning Hebrew, expert at finding good hummus."} },
  { id:"p7", name:"Ana", age:23, flag:"🇧🇷", city:"beer-sheva", color:"#1D9E75", likesYou:true, distanceKm:1.5,
    country:{he:"ברזיל",en:"Brazil"}, langs:["PT","EN"],
    interests:["sport","dance","music"],
    bio:{he:"מסאו פאולו, סטודנטית בבן גוריון. כדורגל, קפוארה, אנרגיה אינסופית.",en:"From São Paulo, studying at BGU. Football, capoeira, endless energy."} },
  { id:"p8", name:"Eitan", age:30, flag:"🇬🇧", city:"tel-aviv", color:"#378ADD", likesYou:false, distanceKm:2.7,
    country:{he:"בריטניה",en:"UK"}, langs:["EN","עברית"],
    interests:["tech","career","outdoors"],
    bio:{he:"מלונדון. מפתח ביום, רץ על הטיילת בערב.",en:"From London. Developer by day, runs the promenade by night."} },
];

/* "fill-in" pickup games — team sports starting soon, short on players */
window.PICKUP = [
  { id:"k1", emoji:"🏀", city:"tel-aviv",   have:5, need:6,  inMin:40,  sport:{he:"כדורסל",en:"Basketball"},        loc:{he:"מגרש גן העיר",en:"Gan Ha'ir court"} },
  { id:"k2", emoji:"⚽", city:"tel-aviv",   have:7, need:8,  inMin:75,  sport:{he:"כדורגל",en:"Football"},          loc:{he:"מגרש פלורנטין",en:"Florentin pitch"} },
  { id:"k3", emoji:"🏐", city:"tel-aviv",   have:4, need:6,  inMin:95,  sport:{he:"כדורעף חופים",en:"Beach volleyball"}, loc:{he:"חוף גורדון",en:"Gordon beach"} },
  { id:"k4", emoji:"🎾", city:"jerusalem",  have:3, need:4,  inMin:25,  sport:{he:"פאדל",en:"Padel"},               loc:{he:"מרכז הספורט",en:"Sports center"} },
  { id:"k5", emoji:"⚽", city:"beer-sheva", have:9, need:10, inMin:55,  sport:{he:"כדורגל 5",en:"5-a-side"},        loc:{he:"קמפוס בן גוריון",en:"BGU campus"} },
  { id:"k6", emoji:"🏀", city:"jerusalem",  have:7, need:10, inMin:110, sport:{he:"כדורסל",en:"Basketball"},        loc:{he:"גבעת רם",en:"Givat Ram"} },
];

window.COUNTRIES = ["France","USA","Argentina","Ukraine","Russia","South Africa","Canada","Brazil","UK","Ethiopia","India","Germany","Mexico","Australia","Other"];

window.I18N = {
  he: {
    dir:"rtl",
    appName:"יאללה", tagline:"החיים החדשים שלך בישראל — החלקה אחת בכל פעם.",
    getStarted:"יאללה, מתחילים", skip:"דלג",
    ob_name:"איך קוראים לך?", ob_age:"בן/בת כמה?", ob_from:"מאיפה עלית?", ob_city:"איפה אתה גר עכשיו?",
    ob_interests:"מה מעניין אותך?", ob_pick:"בחר/י לפחות אחד", ob_go:"מצא לי יאללה",
    nav_discover:"גלה", nav_people:"אנשים", nav_map:"מפה", nav_saved:"שמורים", nav_profile:"פרופיל",
    act_skip:"לא עכשיו", act_super:"סופר", act_save:"שמור", act_like:"אהבתי",
    stamp_yes:"יאללה!", stamp_no:"אולי בפעם אחרת",
    deck_empty_act:"זהו להיום! חזור מאוחר יותר לעוד פעילויות.", deck_empty_ppl:"ראית את כולם! בדוק שוב בקרוב.",
    km:"ק\"מ", attending:"משתתפים", join:"אני בא", joined:"נרשמת ✓", saved_added:"נשמר ל\"שמורים\"",
    detail_about:"על הפעילות", detail_where:"איפה", detail_when:"מתי", share:"שתף", detail_signups:"נרשמו",
    match_title:"יש התאמה!", match_sub:"גם {name} סימן/ה אותך. תתחילו לדבר.",
    match_chat:"שלח הודעה", match_keep:"המשך לגלות",
    filter_title:"סינון", filter_city:"עיר", filter_radius:"מרחק מקסימלי", filter_apply:"החל",
    saved_tab_act:"פעילויות", saved_tab_match:"התאמות", saved_empty:"עדיין לא שמרת כלום — צא לגלות!",
    matches_empty:"אין התאמות עדיין. החלק ימינה כדי להכיר אנשים.",
    profile_from:"עלה/תה מ", profile_langs:"שפות", profile_interests:"תחומי עניין", profile_lang_btn:"English",
    interested_in:"מתעניין/ת ב", langs_label:"מדבר/ת",
    cal_title:"יומן החוגים", cal_back:"חזרה", cal_open:"📅 יומן החוגים",
    cal_empty:"אין חוגים להצגה.", cal_add_google:"➕ Google", cal_add_ics:".ics",
    nav_pickup:"השלמה",
    pickup_title:"השלמת קבוצות", pickup_sub:"ספורט קבוצתי שמתחיל עוד מעט וחסרים בו שחקנים",
    pickup_need:"חסר {n}", pickup_in:"בעוד {n} דק׳", pickup_join:"אני מצטרף/ת", pickup_joined:"נרשמת ✓", pickup_full:"הושלם! 🎉",
    push_view:"צפה", create_btn:"➕ צור פעילות", create_title:"פעילות חדשה",
    cv_name:"שם הפעילות", cv_cat:"קטגוריה", cv_day:"יום", cv_time:"שעה", cv_cap:"כמה אנשים צריך?", cv_loc:"מיקום", cv_submit:"פרסם פעילות",
    myevents_open:"🗓️ האירועים שלי", myevents_title:"האירועים שלי", myevents_empty:"עוד לא יצרת פעילויות.",
    ev_signed:"{a}/{b} נרשמו", ev_spots:"נותרו {n} מקומות", ev_full:"מלא 🎉", ev_filling:"מתמלא",
  },
  en: {
    dir:"ltr",
    appName:"Yalla", tagline:"Your new life in Israel — one swipe at a time.",
    getStarted:"Yalla, let's go", skip:"Skip",
    ob_name:"What's your name?", ob_age:"How old are you?", ob_from:"Where did you make aliyah from?", ob_city:"Where do you live now?",
    ob_interests:"What are you into?", ob_pick:"Pick at least one", ob_go:"Find my Yalla",
    nav_discover:"Discover", nav_people:"People", nav_map:"Map", nav_saved:"Saved", nav_profile:"Profile",
    act_skip:"Not now", act_super:"Super", act_save:"Save", act_like:"Like",
    stamp_yes:"YALLA!", stamp_no:"Maybe later",
    deck_empty_act:"That's it for now! Check back later for more.", deck_empty_ppl:"You've seen everyone! Check back soon.",
    km:"km", attending:"going", join:"I'm in", joined:"You're in ✓", saved_added:"Saved to your list",
    detail_about:"About", detail_where:"Where", detail_when:"When", share:"Share", detail_signups:"Signed up",
    match_title:"It's a match!", match_sub:"{name} liked you too. Start the conversation.",
    match_chat:"Send a message", match_keep:"Keep discovering",
    filter_title:"Filters", filter_city:"City", filter_radius:"Max distance", filter_apply:"Apply",
    saved_tab_act:"Activities", saved_tab_match:"Matches", saved_empty:"Nothing saved yet — go discover!",
    matches_empty:"No matches yet. Swipe right to meet people.",
    profile_from:"Made aliyah from", profile_langs:"Languages", profile_interests:"Interests", profile_lang_btn:"עברית",
    interested_in:"Into", langs_label:"Speaks",
    cal_title:"Activities Calendar", cal_back:"Back", cal_open:"📅 Activities calendar",
    cal_empty:"No activities to show.", cal_add_google:"➕ Google", cal_add_ics:".ics",
    nav_pickup:"Fill-in",
    pickup_title:"Team fill-in", pickup_sub:"Team sports starting soon, short on players",
    pickup_need:"need {n}", pickup_in:"in {n} min", pickup_join:"I'm in", pickup_joined:"You're in ✓", pickup_full:"Filled! 🎉",
    push_view:"View", create_btn:"➕ Create activity", create_title:"New activity",
    cv_name:"Activity name", cv_cat:"Category", cv_day:"Day", cv_time:"Time", cv_cap:"How many people needed?", cv_loc:"Location", cv_submit:"Publish activity",
    myevents_open:"🗓️ My events", myevents_title:"My events", myevents_empty:"No events yet.",
    ev_signed:"{a}/{b} signed up", ev_spots:"{n} spots left", ev_full:"Full 🎉", ev_filling:"Filling up",
  },
};
